config/routes.rb
Rails.application.routes.draw do
  get '/metals', to: "metals#index", as: "metals"
  post '/metals', to: "metals#create", as: "metals_create"
  get '/metals/new', to: "metals#new", as: "metals_new"
  get '/metals/:id', to: "metals#show", as: "metals_show"
  put '/metals/:id', to: "metals#update", as: "metals_update"
  delete'/metals/:id', to: "metals#delete", as: "metals_delete"
  get '/metals/:name/edit', to: "metals#edit", as: "metals_edit"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/metal.rb
class Metal < ApplicationRecord
  Metal.destroy_all
  Metal.create(title:"Gold", price:"3310", desc:"Price per kg")
  Metal.create(title:"Silver", price:"1650", desc:"Price per kg")
  Metal.create(title:"Copper", price:"825", desc:"Price per kg")

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/metals_controller.rb
class MetalsController < ApplicationController



  def index
    @metals = Metal.all
  end

  def create
  end

  def new
    title = params[:title]
    price = params[:price].to_i
    desc = params[:desc]
    @metal = Metal.create(title: title, price: price, desc: desc)
  end

  def show
    id = params[:id]
    @metal = Metal.find id
  end

  def destroy
  end

  def edit
    title = params[:title]
    price = params[:price].to_i
    desc = params[:desc]
    @metal = Metal.update(title: title, price: price, desc: desc)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/metal_helper.rb
module MetalHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SpartaGlobalMetalsRails</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1 class="display-1 bg-info text-center">Mani's Metal Resources</h1>
    <table>
    <%= yield %>
  </body>
</html>

app/views/metal/show.html.erb
<h1>Metal#show</h1>
<p>Find me in app/views/metal/show.html.erb</p>

app/views/metals/_form.html.erb
<%= form_with(model: metal, local: true) do |form| %>
  <% if metal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(metal.errors.count, "error") %> prohibited this metal from being saved:</h2>

      <ul>
      <% metal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :desc %>
    <%= form.text_field :desc %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/metals/destroy.html.erb
<h1>Metal#destroy</h1>
<p>Find me in app/views/metal/destroy.html.erb</p>

app/views/metals/edit.html.erb
<h2 class="jumbotron text-center">#Edit Page</h2>

  <h1 class="display-1 bg-info text-center">Mani's Metal Resources</h1>
  <table>

<div class="panel text-center">
  <%@metals.each do |metal|%>
  <div class="card" style="width: 18rem;">
  <%= image_tag("#{metal.title}.jpg", :alt => "#{metal.title}") %>
  <div class="card-body">
      <h5 class="card-title"><%=metal.title%></h5>
      <p class="card-text"><%=metal.price%></p>
      <p class="card-text"><%=metal.desc%></p>
      <a class="btn btn-primary"><%= link_to 'Create New Metal', %></a>

  </div>
  <%= link_to 'Create New Metal', metals_new_path %>
<%end%>
</div>


</div>


<%= render 'form', metal: @metal %>

app/views/metals/index.html.erb
<h2 class="jumbotron text-center">#Index Page</h2>

<div class="d-inline text-center">
  <%@metals.each do |metal|%>
  <div class="card inline" style="width: 18rem;">
  <%= image_tag("#{metal.title}.jpg", :alt => "#{metal.title}") %>
  <div class="card-body">
      <h5 class="card-title"><%=metal.title%></h5>
      <p class="card-text"><%=metal.price%></p>
      <p class="card-text"><%=metal.desc%></p>
      <%= link_to 'Edit Metal', metals_show_path(metal) %>

  </div>
  <%= link_to 'Create New Metal', metals_new_path %>
<%end%>
</div>


</div>

app/views/metals/new.html.erb
<h2 class="jumbotron text-center">#New Page</h2>


<div class="panel text-center">
  <div class="card" style="width: 18rem;">
  <img class="card-img-top"  alt="New Metal">
  <div class="card-body">
    <form class="" action="metals#create" method="post">
      <input type="text" name="title" placeholder="metal title">
      <input type="float" name="price" placeholder="metal price">
      <input type="text" name="desc" placeholder="metal desc">
      <button type="submit" name="button" value="put">Click to submit</button>
    </form>
  </div>
  <%= link_to 'Click to see all', metals_path %>
</div>


</div>

app/views/metals/show.html.erb
<h2 class="jumbotron text-center">#Show Page</h2>

<div class="panel text-center">
  <div class="card text-center" style="width: 18rem;">
  <%= image_tag("#{@metal.title}.jpg", :alt => "#{@metal.title}") %>
  <div class="card-body">
    <form class="" action="metals#create" method="post">

      <input type="text" name="title" placeholder="<%=@metal.title%>">
      <input type="text" name="price" placeholder="<%=@metal.price%>">
      <input type="text" name="desc" placeholder="<%=@metal.desc%>">
      <button type="submit" name="button" value="submit">Click to submit</button>
    </form>
  </div>
  <%= link_to 'Click to see all', metals_path %>
</div>


</div>